sentTag: sent
smtpHost: smtp.yandex.ru
smtpPort: 587
smtpSecure: false
planfixAccount: tagilcity
planfixAnaliticName: Поминутная работа программиста

# copy above options to config.yml
apiToken:
workspaceId:
smtpLogin:
smtpPassword:
emailFrom:
planfixAuthorName:
